<?php
/**
 * @file
 * Add SMS verification to telephone number field.
 */

/**
 * Explode a multi lines string into an array
 *
 * @param $lines string
 * @return array
 */
function _telephone_sms_verify_explode_multi_lines($lines) {
  return explode("\n", str_replace("\r", "", $lines));
}

/**
 * Add image refresh button to captcha form element
 *
 * @return
 *   The processed element.
 *
 * @see captcha_element_info()
 * @see image_captcha_refresh_element_info_alter()
 */
function _telephone_sms_verify_image_captcha_refresh_after_build_process($element, $form_state) {
  $form_id = $element['#captcha_info']['form_id'];
  if (isset($element['captcha_widgets']['captcha_image'])) {
    // @FIXME
    // theme() has been renamed to _theme() and should NEVER be called directly.
    // Calling _theme() directly can alter the expected output and potentially
    // introduce security issues (see https://www.drupal.org/node/2195739). You
    // should use renderable arrays instead.
    // 
    // 
    // @see https://www.drupal.org/node/2195739
    $element['captcha_widgets']['captcha_refresh'] = array(
      '#markup' => \Drupal::service("renderer")->render(array('#theme' => 'image_captcha_refresh_link', '#url' => 'captcha/refresh/' . $form_id)),
    );
  }
  return $element;
}
