<?php

function telephone_sms_verify_schema() {
  // TODO Add expire
  $schema['telephone_sms_verify_history'] = array(
    'The sms code history for telephone_sms_verify',
    'fields' => array(
      'hid' => array(
        'description' => 'The primary identifier for a history.',
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'phone' => array(
        'description' => 'The number who call the send sms verify code function',
        'type' => 'varchar',
        'length' => 20,
        'not null' => TRUE,
      ),
      'form_id' => array(
        'description' => 'The form id',
        'type' => 'varchar',
        'length' => '255',
        'not null' => TRUE,
      ),
      'sent' => array(
        'description' => 'The Unix timestamp when the sms code was sent.',
        'type' => 'int',
        'not null' => TRUE,
      ),
      'created' => array(
        'description' => 'The Unix timestamp when the sms code was created.',
        'type' => 'int',
        'not null' => TRUE,
      ),
      'code' => array(
        'description' => 'The verify code in the sms was sent.',
        'type' => 'varchar',
        'length' => '10',
        'not null' => TRUE,
      ),
      'content' => array(
        'description' => 'The sms content',
        'type' => 'text',
        'not null' => TRUE,
        'size' => 'medium',
      ),
    ),
    'indexes' => array(
      'phone' => array('phone'),
    ),
    'primary key' => array('hid'),
  );
  return $schema;
}

function telephone_sms_verify_uninstall() {
  variable_del('telephone_sms_verify_sms_template');
  variable_del('telephone_sms_verify_sms_code_expire');
  variable_del('telephone_sms_verify_sms_code_length');
  variable_del('telephone_sms_verify_sms_code_count_down');
  variable_del('telephone_sms_verify_sms_code_max_request_per_hour');
  variable_del('telephone_sms_verify_sms_code_max_request_per_day');
  variable_del('telephone_sms_verify_display_sms_code_verify');
  variable_del('telephone_sms_verify_require_sms_code_verify');
}

function telephone_sms_verify_install() {
  _telephone_sms_verify_variable_initialize();
}

function telephone_sms_verify_update_7100() {
  if (!db_table_exists('telephone_sms_verify_history')) {
    db_create_table('telephone_sms_verify_history', drupal_get_schema_unprocessed('telephone_sms_verify', 'telephone_sms_verify_history'));
  }
}

function telephone_sms_verify_update_7101() {
  _telephone_sms_verify_variable_initialize();
}

function _telephone_sms_verify_variable_initialize() {
  variable_set('telephone_sms_verify_sms_template', DEFAULT_VERIFICATION_MESSAGE_TEMPLATE);
  variable_set('telephone_sms_verify_sms_code_expire', DEFAULT_TELEPHONE_SMS_VERIFY_SMS_CODE_EXPIRE);
  variable_set('telephone_sms_verify_sms_code_length', DEFAULT_TELEPHONE_SMS_VERIFY_SMS_CODE_LENGTH);
  variable_set('telephone_sms_verify_sms_code_count_down', DEFAULT_TELEPHONE_SMS_VERIFY_SMS_CODE_COUNT_DOWN);
  variable_set('telephone_sms_verify_sms_code_max_request_per_hour', DEFAULT_TELEPHONE_SMS_VERIFY_SMS_CODE_MAX_REQUEST_PER_HOUR);
  variable_set('telephone_sms_verify_sms_code_max_request_per_day', DEFAULT_TELEPHONE_SMS_VERIFY_SMS_CODE_MAX_REQUEST_PER_DAY);
  variable_set('telephone_sms_verify_display_sms_code_verify', DEFAULT_TELEPHONE_SMS_VERIFY_DISPLAY_SMS_CODE_VERIFY);
  variable_set('telephone_sms_verify_require_sms_code_verify', DEFAULT_TELEPHONE_SMS_VERIFY_REQUIRE_SMS_CODE_VERIFY);
}
